<?php

return [
    'profile' => [
        'name' => 'Subhradip Roy',
        'headline' => 'Senior Software Engineer',
        'location' => 'Bengaluru',
        'professional_summary' => 'Senior Software Engineer with 10+ years of experience building backend systems, REST APIs, enterprise applications, integrations, and full-stack solutions. Strong PHP background across Yii2, Laravel, and CodeIgniter, with hands-on experience in Node.js, TypeScript, React.js, MySQL, PostgreSQL, Docker, SnapLogic, and Backstage.',
        'focus' => 'Senior Software Engineer roles',
    ],

    'social_links' => [
        'linkedin' => 'https://www.linkedin.com/in/subhradip-roy-6883a479/',
        'github' => null,
    ],

    'contact' => [
        'email' => 'subhradip.1992@gmail.com',
        'phone' => '7407781646',
        'location' => 'Bengaluru',
    ],

    'experience' => [
        [
            'company' => 'Omnicom Global Solutions',
            'location' => 'Bengaluru',
            'position' => 'Senior Software Engineer',
            'start_date' => '2024-06-01',
            'end_date' => null,
            'current' => true,
            'technologies' => [
                'PHP',
                'Yii2',
                'Node.js',
                'TypeScript',
                'REST APIs',
                'SnapLogic',
                'Okta',
                'SCIM 2.0',
                'Backstage',
                'Nuxeo',
                'myDBR',
            ],
            'highlights' => [
                'Owned end-to-end development of Freelancer Timesheet Utility 3.0, from feature planning and technical design through implementation, testing, and delivery.',
                'Built timesheet submission and approval workflows.',
                'Built payroll calculation with overtime rules implementation.',
                'Implemented event-driven audit logging.',
                'Implemented reporting using myDBR.',
                'Led development of Invoices 2.0 features end-to-end including invoice OCR and document transmission to Nuxeo.',
                'Implemented automated transmission of backup documents to Nuxeo.',
                'Designed and developed custom backend plugins for Omnicom OneIDP / Backstage.',
                'Implemented Okta entity synchronization for users and groups.',
                'Implemented Domain Entity Provider and System Entity Provider.',
                'Implemented automated creation of domains and systems based on synchronized users and groups.',
                'Designed and developed SnapLogic APIs consumed by Apple for Vendor Charge Details and supporting backup documents.',
                'Contributed to MCP development for the Omnicom OneIDP platform.',
                'Used GitHub Copilot and OpenAI Codex throughout the software development lifecycle.',
            ],
        ],
        [
            'company' => 'Xiaomi India',
            'location' => 'Bengaluru',
            'position' => 'Software Engineer',
            'start_date' => '2021-09-01',
            'end_date' => '2024-06-01',
            'current' => false,
            'technologies' => [
                'PHP',
                'REST APIs',
                'MySQL',
                'Backend Architecture',
            ],
            'highlights' => [
                'Designed and optimized REST APIs consumed by the Mi-Retail mobile application.',
                'Reduced server response time by 40% through backend/API performance improvements.',
                'Improved backend/API performance contributing to a 20% increase in application downloads.',
                'Developed backend services for the Distributor Management System (DMS).',
                'Automated Warehouse Management System (WMS) processes, reducing manual operational workload by 20%.',
                'Designed and implemented REST APIs for CRM purchase-order workflows used by LFR partners including Reliance and Croma.',
                'Contributed to 20% B2B business growth and 15% reduction in manual workload.',
                'Redesigned and optimized IMEI and Serial Number validation across Xiaomi B2B applications.',
                'Led development and execution of the "Diwali with Mi" nationwide lucky-draw campaign.',
                'Supported prize distribution worth approximately ₹15 crore across states during 2022 and 2023 campaigns.',
                'Led and coordinated a team of 8 engineers while remaining hands-on.',
            ],
        ],
        [
            'company' => 'Gozo Technologies / Gozo Cabs',
            'location' => 'Kolkata',
            'position' => 'Team Lead',
            'start_date' => '2018-11-01',
            'end_date' => '2021-09-01',
            'current' => false,
            'technologies' => [
                'PHP',
                'Yii',
                'MySQL',
                'REST APIs',
                'JavaScript',
                'HTML',
                'CSS',
            ],
            'highlights' => [
                'Led a team of 5 developers.',
                'Delivered backend and frontend components across the GozoCabs platform.',
                'Designed and developed REST APIs for Consumer App, Driver App, and Partner App.',
                'Led backend development using PHP, Yii, and MySQL.',
                'Contributed to frontend development using HTML, CSS, and JavaScript.',
                'Integrated MakeMyTrip, Goibibo, and Yatra into the GozoCabs platform.',
                'Increased daily bookings from approximately 1,200 to 2,200+, an increase of more than 80%.',
                'Coordinated technical execution, requirements, troubleshooting, stakeholder communication, and delivery.',
                'Contributed to a 25% reduction in project costs.',
                'Contributed to a 50% improvement in client satisfaction.',
            ],
        ],
        [
            'company' => 'Epitech Internet Pvt. Ltd.',
            'location' => 'Kolkata',
            'position' => 'Software Developer',
            'start_date' => '2017-09-01',
            'end_date' => '2018-11-01',
            'current' => false,
            'technologies' => [
                'C#',
                'SQLite',
                'REST APIs',
            ],
            'highlights' => [
                'Developed SaaS billing and stock management applications for INDANE and HP LPG dealers.',
                'Used C# and SQLite for application development.',
                'Designed and implemented REST API integrations for an LPG inspection mobile application.',
                'Managed onsite installation, deployment, maintenance, troubleshooting, and production support.',
                'Supported onboarding of 12 major LPG dealers during pilot launch.',
                'Supported 13 additional dealers across Kolkata.',
                'Contributed to solutions generating approximately ₹1 crore annual revenue.',
            ],
        ],
    ],

    'skills' => [
        'backend' => [
            'PHP',
            'Yii2',
            'Laravel',
            'CodeIgniter',
            'Node.js',
            'REST APIs',
        ],
        'frontend' => [
            'React.js',
            'TypeScript',
            'JavaScript',
            'HTML/CSS',
        ],
        'databases_and_caching' => [
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'Redis',
        ],
        'integration_and_identity' => [
            'SnapLogic iPaaS',
            'Okta',
            'SCIM 2.0',
            'Nuxeo',
            'MCP',
        ],
        'platforms_and_architecture' => [
            'Backstage',
            'Microservices',
            'Enterprise Integration',
            'Software Architecture',
            'API Design',
        ],
        'ai_and_developer_productivity' => [
            'GitHub Copilot',
            'Git',
            'Generative AI',
            'AI-assisted Development',
        ],
        'tools_and_leadership' => [
            'Docker',
            'Git',
            'Team Leadership',
            'Stakeholder Management',
            'Cross-functional Collaboration',
        ],
    ],

    'projects' => [
        [
            'title' => 'Freelancer Timesheet Utility 3.0',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Enterprise freelancer timesheet and payroll-processing platform with end-to-end development from planning through delivery.',
            'technologies' => [
                'PHP',
                'Yii2',
                'MySQL',
                'REST APIs',
                'Okta',
                'SnapLogic',
                'React',
            ],
            'features' => [
                'Timesheet submission and approval workflows',
                'Payroll calculation engine',
                'Overtime rules implementation (California and Federal)',
                'Multi-rate handling (hourly and weekly)',
                'Automated approval/rejection/redirect workflows',
                'Event-driven audit logging',
                'Reporting via myDBR',
            ],
            'highlights' => [
                'Implemented California and Federal overtime rules.',
                'Achieved automated payroll calculations.',
                'Delivered timesheet approval workflows.',
                'End-to-end ownership from planning to delivery.',
            ],
        ],
        [
            'title' => 'Omnicom OneIDP / Backstage',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Developer portal and identity-management integration built around Backstage with SCIM 2.0 compliance and Okta integration.',
            'technologies' => [
                'Backstage',
                'SCIM 2.0',
                'Okta',
                'Azure AD',
                'Node.js',
                'TypeScript',
                'REST APIs',
            ],
            'features' => [
                'SCIM 2.0 compliant backend functionality',
                'User and group provisioning workflows',
                'Bearer-token validation',
                'IP whitelisting',
                'Event-driven audit logging',
                'Custom Backstage plugins for Okta integration',
                'Domain and system entity providers',
                'Automated domain and system creation',
            ],
            'highlights' => [
                'Designed custom Backstage backend plugins for enterprise identity management.',
                'Implemented SCIM 2.0 compliance for user/group synchronization.',
                'Built automated provisioning workflows for Okta users and groups.',
            ],
        ],
        [
            'title' => 'Invoices 2.0',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Enterprise invoice processing platform with OCR and document transmission capabilities.',
            'technologies' => [
                'PHP',
                'Yii2',
                'MySQL',
                'OCR Technology',
                'Nuxeo',
                'REST APIs',
            ],
            'features' => [
                'Invoice OCR processing',
                'Document transmission to Nuxeo',
                'Vendor Charge Detail backup generation',
                'Automated backup document transmission',
            ],
            'highlights' => [
                'Led end-to-end development of Invoices 2.0 features.',
                'Implemented invoice OCR for automated data extraction.',
                'Automated document transmission to Nuxeo DMS.',
            ],
        ],
        [
            'title' => 'Vendor Charge Detail APIs',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Enterprise API integration layer for vendor charge detail management implemented using SnapLogic.',
            'technologies' => [
                'SnapLogic',
                'MySQL',
                'REST APIs',
                'SQL',
            ],
            'highlights' => [
                'Designed and developed SnapLogic APIs consumed by Apple.',
                'Implemented vendor charge detail data processing.',
                'Integrated with backup document workflows.',
            ],
        ],
    ],

    'certifications' => [
        [
            'title' => 'Building PHP Applications with Generative AI',
        ],
        [
            'title' => 'Demystifying Agentic AI with ChatGPT',
        ],
        [
            'title' => 'Build Your Own GPTs',
        ],
        [
            'title' => 'Managing Cross-Functional Collaboration as a Leader',
        ],
    ],

    'awards' => [
        [
            'title' => 'The OG-Star of the Quarter',
            'issuer' => 'Technology Solutions OGS, Omnicom Global Solutions',
            'date' => '2026-01-01',
        ],
        [
            'title' => 'Annalectual of the Quarter',
            'issuer' => 'Technology Solutions OGS, Omnicom Global Solutions',
            'date' => '2025-01-01',
        ],
        [
            'title' => 'Fire Fighter Award',
            'issuer' => 'Xiaomi India',
            'date' => '2023-01-01',
        ],
        [
            'title' => 'Certificate of Appreciation',
            'issuer' => 'Gozo Technologies',
            'date' => '2019-01-01',
        ],
    ],

    'education' => [
        [
            'degree' => 'B.Tech in Computer Science',
            'institution' => 'Narula Institute of Technology, Kolkata',
            'start_year' => 2010,
            'end_year' => 2014,
        ],
    ],
];
