<?php

return [
    'profile' => [
        'name' => 'Subhradip Roy',
        'headline' => 'Senior Software Engineer',
        'location' => 'Bengaluru',
        'professional_summary' => 'Senior Software Engineer with 10+ years of experience building backend systems, REST APIs, enterprise applications, integrations, and full-stack solutions. Strong PHP background across Yii2, Laravel, and CodeIgniter, with hands-on experience in Node.js, TypeScript, React.js, MySQL, PostgreSQL, Docker, SnapLogic, and Backstage.',
        'focus' => 'Senior Software Engineer roles',
    ],

    'social_links' => [
        'linkedin' => 'https://www.linkedin.com/in/subhradip-roy-6883a479/',
        'github' => null,
    ],

    'contact' => [
        'email' => 'subhradip.1992@gmail.com',
        'phone' => '7407781646',
        'location' => 'Bengaluru',
    ],

    'experience' => [
        [
            'company' => 'Omnicom Global Solutions',
            'location' => 'Bengaluru',
            'position' => 'Senior Software Engineer',
            'start_date' => '2024-06-01',
            'end_date' => null,
            'current' => true,
            'technologies' => [
                'PHP',
                'Yii2',
                'Node.js',
                'TypeScript',
                'REST APIs',
                'SnapLogic',
                'Okta',
                'SCIM 2.0',
                'Backstage',
                'Nuxeo',
                'myDBR',
            ],
            'highlights' => [
                'Owned major areas of Freelancer Timesheet Utility 3.0 across feature planning, technical design, implementation, testing, and delivery.',
                'Engineered timesheet lifecycle workflows including validation, submission, review, approval/rejection, recall, redirect, and posting.',
                'Implemented configurable Federal and California overtime calculation logic, including California daily overtime and double-time calculations.',
                'Developed event-driven audit logging and strengthened application security through XSS remediation and access-control improvements.',
                'Implemented reporting using myDBR.',
                'Developed and enhanced Invoices 2.0 vendor charge and document workflows, including Nuxeo integration.',
                'Implemented vendor charge document upload, re-upload, deletion, tracking, and supporting-document workflows.',
                'Designed and developed custom backend plugins for Omnicom OneIDP / Backstage.',
                'Implemented Okta entity synchronization for users and groups.',
                'Implemented Domain Entity Provider and System Entity Provider.',
                'Implemented automated creation of domains and systems based on synchronized users and groups.',
                'Designed and developed SnapLogic APIs consumed by Apple for Vendor Charge Details and supporting backup documents.',
                'Contributed to MCP development for the Omnicom OneIDP platform.',
                'Used GitHub Copilot and OpenAI Codex throughout the software development lifecycle.',
            ],
        ],
        [
            'company' => 'Xiaomi India',
            'location' => 'Bengaluru',
            'position' => 'Software Engineer',
            'start_date' => '2021-09-01',
            'end_date' => '2024-06-01',
            'current' => false,
            'technologies' => [
                'PHP',
                'REST APIs',
                'MySQL',
                'Backend Architecture',
            ],
            'highlights' => [
                'Designed and optimized REST APIs consumed by the Mi-Retail mobile application.',
                'Reduced server response time by 40% through backend/API performance improvements.',
                'Improved backend/API performance contributing to a 20% increase in application downloads.',
                'Developed backend services for the Distributor Management System (DMS).',
                'Automated Warehouse Management System (WMS) processes, reducing manual operational workload by 20%.',
                'Designed and implemented REST APIs for CRM purchase-order workflows used by LFR partners including Reliance and Croma.',
                'Contributed to 20% B2B business growth and 15% reduction in manual workload.',
                'Redesigned and optimized IMEI and Serial Number validation across Xiaomi B2B applications.',
                'Led development and execution of the "Diwali with Mi" nationwide lucky-draw campaign.',
                'Supported prize distribution worth approximately ₹15 crore across states during 2022 and 2023 campaigns.',
                'Led and coordinated a team of 8 engineers while remaining hands-on.',
            ],
        ],
        [
            'company' => 'Gozo Technologies / Gozo Cabs',
            'location' => 'Kolkata',
            'position' => 'Team Lead',
            'start_date' => '2018-11-01',
            'end_date' => '2021-09-01',
            'current' => false,
            'technologies' => [
                'PHP',
                'Yii',
                'MySQL',
                'REST APIs',
                'JavaScript',
                'HTML',
                'CSS',
            ],
            'highlights' => [
                'Led a team of 5 developers.',
                'Delivered backend and frontend components across the GozoCabs platform.',
                'Designed and developed REST APIs for Consumer App, Driver App, and Partner App.',
                'Led backend development using PHP, Yii, and MySQL.',
                'Contributed to frontend development using HTML, CSS, and JavaScript.',
                'Integrated MakeMyTrip, Goibibo, and Yatra into the GozoCabs platform.',
                'Increased daily bookings from approximately 1,200 to 2,200+, an increase of more than 80%.',
                'Coordinated technical execution, requirements, troubleshooting, stakeholder communication, and delivery.',
                'Contributed to a 25% reduction in project costs.',
                'Contributed to a 50% improvement in client satisfaction.',
            ],
        ],
        [
            'company' => 'Epitech Internet Pvt. Ltd.',
            'location' => 'Kolkata',
            'position' => 'Software Developer',
            'start_date' => '2017-09-01',
            'end_date' => '2018-11-01',
            'current' => false,
            'technologies' => [
                'C#',
                'SQLite',
                'REST APIs',
            ],
            'highlights' => [
                'Developed SaaS billing and stock management applications for INDANE and HP LPG dealers.',
                'Used C# and SQLite for application development.',
                'Designed and implemented REST API integrations for an LPG inspection mobile application.',
                'Managed onsite installation, deployment, maintenance, troubleshooting, and production support.',
                'Supported onboarding of 12 major LPG dealers during pilot launch.',
                'Supported 13 additional dealers across Kolkata.',
                'Contributed to solutions generating approximately ₹1 crore annual revenue.',
            ],
        ],
    ],

    'skills' => [
        'backend' => [
            'PHP',
            'Yii2',
            'Laravel',
            'CodeIgniter',
            'Node.js',
            'REST APIs',
        ],
        'frontend' => [
            'React.js',
            'TypeScript',
            'JavaScript',
            'HTML/CSS',
        ],
        'databases_and_caching' => [
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'Redis',
        ],
        'integration_and_identity' => [
            'SnapLogic iPaaS',
            'Okta',
            'SCIM 2.0',
            'Nuxeo',
            'MCP',
        ],
        'platforms_and_architecture' => [
            'Backstage',
            'Microservices',
            'Enterprise Integration',
            'Software Architecture',
            'API Design',
        ],
        'ai_and_developer_productivity' => [
            'GitHub Copilot',
            'Git',
            'Generative AI',
            'AI-assisted Development',
        ],
        'tools_and_leadership' => [
            'Docker',
            'Git',
            'Team Leadership',
            'Stakeholder Management',
            'Cross-functional Collaboration',
        ],
    ],

    'projects' => [
        [
            'title' => 'Freelancer Timesheet Utility 3.0',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Enterprise freelancer timesheet, approval, payroll calculation, and workforce management platform. Contributed extensively across core business workflows, calculation logic, authentication, authorization, audit logging, security, and enterprise integrations.',
            'technologies' => [
                'PHP',
                'Yii2',
                'MySQL',
                'REST APIs',
                'Okta',
                'ReactJS',
                'JavaScript',
            ],
            'features' => [
                'End-to-end timesheet lifecycle including validation, submission, review, approval, rejection, recall, redirect, and posting',
                'Timesheet processing and calculation-preview workflows with estimated-pay calculation, filtering, and exports',
                'Configurable Federal and California overtime calculation logic',
                'California daily overtime and double-time calculation support',
                'Overtime-rule configuration integrated with freelancer rate management',
                'Event-driven audit logging for timesheet, authentication, posting, registration, and rate-management events',
                'ATH (Authorization to Hire) workflows and CRUD functionality',
                'Okta-based authentication and identity integration',
                'Two-factor authentication and account security capabilities',
                'Role-based and system-group-based access control',
                'Manager workflows for pending, reviewed, and approval-related timesheets',
                'Application-wide XSS remediation across backend, frontend, and email templates',
            ],
            'highlights' => [
                'Implemented Federal and California overtime calculation logic, including California daily overtime and double-time calculations.',
                'Engineered core timesheet processing workflows covering validation, submission, review, approval/rejection, recall, redirect, and posting.',
                'Developed calculation-preview and estimated-pay processing capabilities for payroll workflows.',
                'Built event-driven audit logging across timesheet, authentication, posting-session, freelancer registration, and rate-management workflows.',
                'Implemented Okta authentication, two-factor authentication, and role-based access controls.',
                'Developed ATH (Authorization to Hire) workflows and freelancer rate-management capabilities.',
                'Led extensive XSS security remediation across backend views, frontend views, and email templates.',
            ],
        ],
        [
            'title' => 'Omnicom OneIDP / Backstage',
            'company' => 'Omnicom Global Solutions',

            'description' =>
                'Enterprise developer portal and identity-management platform built on Backstage. ' .
                'Contributed to custom backend modules, Okta synchronization, SCIM 2.0 provisioning, ' .
                'Domain and System entity providers, automated entity creation, permissions, and MCP integration.',

            'technologies' => [
                'Backstage',
                'Node.js',
                'TypeScript',
                'SCIM 2.0',
                'Okta',
                'REST APIs',
                'PostgreSQL',
                'MCP',
            ],

            'features' => [
                'Custom Backstage backend modules and entity providers',
                'Okta user and group synchronization',
                'Automated Okta-backed entity provisioning',
                'SCIM 2.0 identity provisioning',
                'Domain entity provider with database persistence',
                'System entity provider with automated system creation',
                'Domain ownership and naming management',
                'Okta group hierarchy and parent relationship mapping',
                'Role and permission controls for synchronization operations',
                'Manual Okta synchronization triggers',
                'Entity refresh and synchronization lifecycle management',
                'MCP server and developer portal tooling integration',
            ],

            'highlights' => [
                'Designed and developed custom Backstage backend modules for enterprise identity and entity management.',
                'Built Okta user and group synchronization with configurable sync controls, permissions, entity refresh, and identity mapping.',
                'Implemented SCIM 2.0 backend capabilities including authentication middleware, validation, routing, and catalog integration.',
                'Designed Domain and System entity providers with database persistence and automated entity provisioning.',
                'Implemented automated domain and system creation based on synchronized enterprise identity structures.',
                'Developed domain ownership, naming, group hierarchy, and TLA provisioning workflows.',
                'Contributed to MCP integration including catalog, TechDocs, templates, and Temporal-oriented tooling.',
            ],
        ],
        [
            'title' => 'Vendor Charge Detail APIs',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Enterprise REST API integration layer built with SnapLogic for Vendor Charge Detail retrieval, release-date processing, pagination, and document retrieval.',
            'technologies' => [
                'SnapLogic',
                'REST APIs',
                'MySQL',
                'SQL',
                'Nuxeo',
            ],
            'features' => [
                'Vendor Charge Detail REST APIs',
                'Release-date range based transaction retrieval',
                'Pagination using page size and page index',
                'GroupingKey based transaction and document retrieval',
                'Release status and release timestamp processing',
                'Vendor, project, company, charge type, and transaction metadata retrieval',
                'Dynamic PDF download endpoint generation',
                'Nuxeo document retrieval integration',
                'Supporting document workflow integration',
            ],
            'highlights' => [
                'Designed and developed SnapLogic REST APIs consumed by Apple for Vendor Charge Detail processing and supporting document retrieval.',
                'Implemented paginated transaction retrieval with release-date filtering and result metadata.',
                'Implemented GroupingKey-based document retrieval workflows connecting Vendor Charge Details with supporting documents.',
                'Integrated API responses with Nuxeo-backed PDF document retrieval.',
                'Exposed vendor, project, company, charge type, transaction, and release metadata through the API layer.',
            ],
        ],

        [
            'title' => 'Invoices 2.0',
            'company' => 'Omnicom Global Solutions',
            'description' => 'Enterprise invoice and vendor charge document-processing platform integrating Yii2 and Nuxeo. Contributed extensively to vendor charge management, document processing, upload workflows, access control, and enterprise document integration.',
            'technologies' => [
                'PHP',
                'Yii2',
                'MySQL',
                'Nuxeo',
                'REST APIs',
                'JavaScript',
            ],
            'features' => [
                'Vendor Charge Details management',
                'Nuxeo document upload and tracking',
                'Document upload and re-upload workflows',
                'Support document management',
                'Production charge PDF override workflows',
                'Document deletion',
                'Grouped vendor charge pagination and filtering',
                'Vendor charge export',
                'Charge-type based document source handling',
                'Release and unrelease workflows',
                'Release-user tracking',
                'Administrative access control',
            ],
            'highlights' => [
                'Developed and enhanced Vendor Charge Details workflows including grouped pagination, filtering, export, and charge management.',
                'Integrated Nuxeo document management for vendor charge uploads, re-uploads, tracking, deletion, and support documents.',
                'Redesigned the document upload workflow and refactored Nuxeo document processing logic.',
                'Implemented support-document overrides for production charge PDFs.',
                'Enhanced charge release workflows with unrelease capability and release-user tracking.',
                'Strengthened administrative access control for vendor charge management.',
            ],
        ],
        [
            'title' => 'TBWA Okta OAuth',
            'company' => 'TBWA / Omnicom',
            'description' => 'Reusable PHP authentication package designed to provide standardized Okta-based authentication across PHP applications through a Composer-based integration layer.',
            'technologies' => [
                'PHP',
                'Okta',
                'OAuth',
                'Composer',
                'Yii2',
                'REST APIs',
            ],
            'features' => [
                'Reusable Okta authentication package for PHP applications',
                'Centralized authentication handling through AuthHandle',
                'Composer-based package integration',
                'Authentication event handling',
                'User and authentication data models',
                'Database migrations supporting authentication functionality',
                'Reusable configuration and integration structure',
                'Package documentation and integration guidance',
            ],
            'highlights' => [
                'Designed and developed a reusable Okta authentication package for PHP applications.',
                'Built the core authentication handling layer and standardized Okta integration through AuthHandle.',
                'Packaged authentication functionality for reusable Composer-based integration across applications.',
                'Implemented authentication events, user/authentication models, and supporting database migrations.',
                'Created package documentation and integration guidance to support adoption across PHP applications.',
            ],
        ],
        [
            'title' => 'Mi-Retail / Xiaomi B2B Platforms',
            'company' => 'Xiaomi India',
            'description' => 'Enterprise retail, distributor, warehouse, CRM, and after-sales backend platform supporting Xiaomi B2B and retail operations.',
            'technologies' => [
                'PHP',
                'REST APIs',
                'MySQL',
                'Backend Architecture',
            ],
            'features' => [
                'Mi-Retail mobile application backend services',
                'Distributor Management System (DMS)',
                'Warehouse Management System (WMS) automation',
                'CRM purchase-order workflows',
                'IMEI and serial-number validation',
                'B2B partner integrations',
            ],
            'highlights' => [
                'Designed and optimized REST APIs consumed by the Mi-Retail mobile application.',
                'Reduced server response time by 40% through backend and API performance improvements.',
                'Developed backend services for the Distributor Management System.',
                'Automated Warehouse Management System processes to reduce manual operational workload.',
                'Designed REST APIs for CRM purchase-order workflows used by LFR partners including Reliance and Croma.',
                'Led development and execution of the Diwali with Mi nationwide lucky-draw campaign.',
                'Led and coordinated a team of 8 engineers while remaining hands-on.',
            ],
        ],
        [
            'title' => 'GozoCabs Platform',
            'company' => 'Gozo Technologies / Gozo Cabs',
            'description' => 'Multi-application cab booking platform spanning consumer, driver, and partner applications with travel-industry integrations.',
            'technologies' => [
                'PHP',
                'Yii',
                'MySQL',
                'REST APIs',
                'JavaScript',
                'HTML',
                'CSS',
            ],
            'features' => [
                'Consumer, Driver, and Partner application APIs',
                'Cab booking and partner workflows',
                'Travel-platform integrations',
                'Backend and frontend application development',
            ],
            'highlights' => [
                'Led a team of 5 developers while remaining hands-on with backend development.',
                'Designed and developed REST APIs for Consumer, Driver, and Partner applications.',
                'Led backend development using PHP, Yii, and MySQL.',
                'Integrated MakeMyTrip, Goibibo, and Yatra into the GozoCabs platform.',
                'Increased daily bookings from approximately 1,200 to more than 2,200.',
                'Coordinated technical execution, requirements, troubleshooting, stakeholder communication, and delivery.',
            ],
        ],
        [
            'title' => 'LPG SaaS Billing & Inspection Platform',
            'company' => 'Epitech Internet Pvt. Ltd.',
            'description' => 'SaaS billing, stock management, and inspection integration solutions for LPG dealers and field operations.',
            'technologies' => [
                'C#',
                'SQLite',
                'REST APIs',
            ],
            'features' => [
                'SaaS billing applications',
                'Stock management applications',
                'LPG inspection mobile application API integration',
                'Onsite deployment and production support',
            ],
            'highlights' => [
                'Developed SaaS billing and stock management applications for INDANE and HP LPG dealers.',
                'Designed and implemented REST API integrations for an LPG inspection mobile application.',
                'Managed onsite installation, deployment, maintenance, troubleshooting, and production support.',
                'Supported onboarding of 12 major LPG dealers during the pilot launch.',
                'Supported additional dealer deployments across Kolkata.',
            ],
        ],
    ],

    'certifications' => [
        [
            'title' => 'Building PHP Applications with Generative AI',
        ],
        [
            'title' => 'Demystifying Agentic AI with ChatGPT',
        ],
        [
            'title' => 'Build Your Own GPTs',
        ],
        [
            'title' => 'Managing Cross-Functional Collaboration as a Leader',
        ],
    ],

    'awards' => [
        [
            'title' => 'The OG-Star of the Quarter',
            'issuer' => 'Technology Solutions OGS, Omnicom Global Solutions',
            'date' => '2026-01-01',
        ],
        [
            'title' => 'Annalectual of the Quarter',
            'issuer' => 'Technology Solutions OGS, Omnicom Global Solutions',
            'date' => '2025-01-01',
        ],
        [
            'title' => 'Fire Fighter Award',
            'issuer' => 'Xiaomi India',
            'date' => '2023-01-01',
        ],
        [
            'title' => 'Certificate of Appreciation',
            'issuer' => 'Gozo Technologies',
            'date' => '2019-01-01',
        ],
    ],

    'education' => [
        [
            'degree' => 'B.Tech in Computer Science',
            'institution' => 'Narula Institute of Technology, Kolkata',
            'start_year' => 2010,
            'end_year' => 2014,
        ],
    ],
];